name: shikomi_gui
description: 定型文を登録し、キーで貼り付けるデスクトップアプリ。
publish_to: none
version: 0.0.2+2
environment:
  sdk: ^3.13.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dbus: ^0.7.12
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/app-icon.png
