name: Unit Core

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit-core:
    name: unit-core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: cargo test (shikomi-core)
        run: cargo test -p shikomi-core
